# Generated by Django 3.2.9 on 2021-11-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211119_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='universe',
            options={'ordering': ['-id']},
        ),
    ]
