# Generated by Django 3.2.9 on 2021-11-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211119_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.universe'),
        ),
    ]
